package com.forum.messages.entities;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonIgnore;

@Entity
@Table(name="forumthreads")
public class ForumThread {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name="thread_id")
	private int thread_id;
	
	@NotNull
	@Column(name="title")
	private String title;
	
	@NotNull
	@Column(name="locked")
	private int locked;
	
	@Column
	private int posts; //posts are autogenerated through a trigger on insert and on delete in mySql in table thread_messages
	
	@OneToMany(mappedBy="forumThread")
	@JsonIgnore
	private List <ThreadMessage> threadMessages;

	public ForumThread() {}
	
	public ForumThread( String title) {
		this.title = title;
		this.locked = 0;
		this.posts = 0;
	}

	public int getThread_id() {
		return thread_id;
	}

	public void setThread_id(int thread_id) {
		this.thread_id = thread_id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public int getLocked() {
		return locked;
	}

	public void setLocked(int locked) {
		this.locked = locked;
	}

	public int getPosts() {
		return posts;
	}

	
	
}
